# Generated by Django 2.2.6 on 2019-10-19 15:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
    ]
