# Generated by Django 2.2.6 on 2019-10-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191019_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentaire',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Comentaire',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
