# Generated by Django 2.2.6 on 2019-10-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191019_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentaire',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='comment'),
        ),
    ]
